- name: Configure MongoDB
  hosts: db
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.132.15.193
  tasks:
    - name: Change mongo file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
    - name: restart mongod
      become: true
      service: name=mongod state=restarted
