- name: Deploy app
  hosts: app
  vars:
    db_host: 10.132.15.193
  become: true
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/sarmirim/reddit
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/sarmirim/reddit

  handlers:
    - name: reload puma
      become: true
      systemd: name=puma state=restarted
