---
- name: Configure MongoDB
  hosts: db
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.132.0.59
  tags: db-tag
  tasks:
    - name: Change mongo file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
    - name: restart mongod
      become: true
      service: name=mongod state=restarted

- name: Configure app
  hosts: app
  vars:
    db_host: 10.132.0.59
  tags: app-tag
  become: true
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/sarmirim/db_config

    - name: enable puma
      become: true
      systemd: name=puma enabled=yes

  handlers:
    - name: reload puma
      become: true
      systemd: name=puma state=restarted

- name: Deploy app
  hosts: app
  vars:
    db_host: 10.132.0.59
  tags: deploy-tag
  become: true
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/sarmirim/reddit
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/sarmirim/reddit
